#!/bin/bash

if [ $# -le 2 ]; then
    echo "[usage] ./run <backend> <env> [other options]"
    echo $#
    exit 1
fi

BACKEND=$1
shift
ENV=$1
shift

cd dqn
python3 train_agent.py --backend $BACKEND --env $ENV $@
