#!/bin/bash

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
    echo "./test_all <backend> <env> <target_dir_path>"
    exit 1
fi

NUM_PROC=10
RUN_COUNT=0

BACKEND=$1
shift
ENV=$1
shift
TARGET_DIR=$1
shift
OTHERARGS=$@

LOG_FILENAME="${TARGET_DIR}/test_log_${BACKEND}_${ENV}_`date "+%Y%m%d_%H%M%S"`"
LOG=${LOG_FILENAME}.log
echo "backend  : ${BACKEND}" > $LOG
echo "env      : ${ENV}" >> $LOG
echo "targetdir: ${TARGET_DIR}" >> $LOG

for file in `dir -b ${TARGET_DIR}/*.dat`; do

    DAT_NAME=${file##*/}

    if [[ $DAT_NAME =~ ([0-9]{1,}) ]]; then
        step=${BASH_REMATCH[1]}
    else
        step=0
    fi

    if [ $step -ge 20000000 ]; then
        RUN_LOG=${LOG_FILENAME}_${step}.log
        echo "${DAT_NAME}: `./test_run $BACKEND $ENV $file --test_episodes 100 $@ |tee ${RUN_LOG} |grep 'test end'`" >> ${LOG} &

        let RUN_COUNT++
        echo "test_run ${step} .."

        if [ $(( RUN_COUNT%${NUM_PROC} )) -eq 0 ]; then
            wait
        fi
    fi
done
wait
