#!/bin/bash

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
    echo "./test_run <backend> <env> <param_file_name>"
    exit 1
fi
BACKEND=$1
shift
ENV=$1
shift
FILE_NAME=$1
shift
./run --backend $BACKEND --env $ENV --file_name $FILE_NAME --test  --test_recording --test_recording_q_value --video_freq 1 --logdir /tmp $@
