#!/bin/bash

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
    echo "./test_all <backend> <env> <target_dir_path>"
    exit 1
fi

NUM_PROC=10
RUN_COUNT=0

BACKEND=$1
shift
ENV=$1
shift
TARGET_DIR=$1
shift
OTHERARGS=$@

LOG_FILENAME="${TARGET_DIR}/test_log_${BACKEND}_${ENV}_`date "+%Y%m%d_%H%M%S"`"

echo "backend  : ${BACKEND}" > $LOG_FILENAME
echo "env      : ${ENV}" >> $LOG_FILENAME
echo "targetdir: ${TARGET_DIR}" >> $LOG_FILENAME

for file in `dir -b ${TARGET_DIR}/*.dat`; do
    RUN_LOG=${LOG_FILENAME}_${RUN_COUNT}.log
    echo "${file##*/}: `./test_run $BACKEND $ENV $file --test_episodes 100 $@ |tee ${RUN_LOG} |grep 'test end'`" >> ${LOG_FILENAME}.log &

    let RUN_COUNT++
    echo "test_run ${RUN_COUNT}.."

    sleep 5
    if [ $(( RUN_COUNT%${NUM_PROC} )) -eq 0 ]; then
        wait
    fi
done
