#!/bin/bash

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
    echo "./test_run <backend> <env> <param_file_name>"
    exit 1
fi

NUM_PROC=10
RUN_COUNT=0

BACKEND=$1
shift
ENV=$1
shift
TARGET_DIR=$1
shift
OTHERARGS=$@

LOG_FILENAME="log_${BACKEND}_${ENV}_`date "+%Y%m%d_%H%M%S"`.log"

echo "backend  : ${BACKEND}" > $LOG_FILENAME
echo "env      : ${ENV}" >> $LOG_FILENAME
echo "targetdir: ${TARGET_DIR}" >> $LOG_FILENAME

for file in `dir -b ${TARGET_DIR}/*.dat`; do
    echo "${file##*/}: `./test_run $BACKEND $ENV $file $@ |grep 'test end'`" >> $LOG_FILENAME &
    sleep 5

    let RUN_COUNT++
    if [ $(( RUN_COUNT%${NUM_PROC} )) -eq 0 ]; then
        wait
    fi
done
