FROM nvidia/cuda:8.0-cudnn5-devel

RUN apt-get update \
 && apt-get install -y python-numpy python-dev cmake zlib1g-dev libjpeg-dev xvfb libav-tools xorg-dev python-opengl libboost-all-dev libsdl2-dev swig git python3-pip
RUN pip3 install --upgrade pip
RUN pip3 install mxnet-cu80mkl==1.0.0
RUN pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.2.1-cp35-cp35m-linux_x86_64.whl
RUN pip3 install sk-video
RUN pip3 install opencv-python
RUN pip3 install Pillow
