#
#  For CNTK == 2.3.1
#
FROM nvidia/cuda:8.0-cudnn6-devel

RUN apt-get update \
 && apt-get install -y python-numpy python-dev cmake zlib1g-dev libjpeg-dev xvfb libav-tools xorg-dev python-opengl libboost-all-dev libsdl2-dev swig git python3-pip zip openmpi-bin
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.4.1-cp35-cp35m-linux_x86_64.whl
RUN pip3 install https://cntk.ai/PythonWheel/GPU/cntk-2.3.1-cp35-cp35m-linux_x86_64.whl \
 && ln -s /usr/lib/openmpi/lib/libmpi.so /usr/lib/openmpi/lib/libmpi.so.12 \
 && echo export LD_LIBRARY_PATH=/usr/lib/openmpi/lib:$LD_LIBRARY_PATH >> /root/.bashrc
RUN git clone https://github.com/keras-team/keras.git -q \
 && cd keras \
 && git checkout -b 2.1.2 -q \
 && python3 setup.py install
RUN pip3 install sk-video opencv-python Pillow h5py

