#
#  For Tensorflow 1.5.0
#
FROM nvidia/cuda:9.0-cudnn7-devel

RUN apt-get update \
 && apt-get install -y python-numpy python-dev cmake zlib1g-dev libjpeg-dev xvfb libav-tools xorg-dev python-opengl libboost-all-dev libsdl2-dev swig git python3-pip zip
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.5.0-cp35-cp35m-linux_x86_64.whl
RUN git clone https://github.com/keras-team/keras.git -q \
 && cd keras \
 && git checkout -b 2.1.2 -q \
 && python3 setup.py install
RUN pip3 install sk-video opencv-python Pillow h5py
