#!/bin/bash

if [ $# = 0 ]; then
    echo "./run_docker docker_image:tag [--logdir <logdir path>]"
    exit 1
fi
if [ $# -gt 3 ]; then
    echo "./run_docker docker_image:tag [--logdir <logdir path>]"
    exit 1
fi

CURDIR=`pwd`

image_name=$1

declare -a a_dirs=();
a_dirs=${CURDIR//\// }

root_dir=""

for dir in ${a_dirs};
do
    root_dir="${root_dir}/${dir}"
    if [ "$dir" = "DQN" ]; then
        break
    fi
done

log_dir="/tmp"

until [ $# = 0 ]
do
    arg=$1
    if [ "$arg" = "--logdir" ]; then
        shift
        log_dir=$1
        break
    fi
    shift
done
echo "mount /mnt/DQN ------> ${root_dir}"
echo "mount /mnt/log_dir --> ${log_dir}"
nvidia-docker run -it -v ${root_dir}:/mnt/DQN -v ${log_dir}:/mnt/log_dir $image_name
